### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Gouet** [sabinadams/aurora#14]
Hi,

After updated the new version prisma-aurora@1.2.1

It throw me an error :
```
aurora                        
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'fs-jetpack'
Require stack:
- /usr/local/lib/node_modules/prisma-aurora/node_modules/@prisma/sdk/dist/utils/jestContext.js
- /usr/local/lib/node_modules/prisma-aurora/node_modules/@prisma/sdk/dist/index.js
- /usr/local/lib/node_modules/prisma-aurora/lib/helpers/parseSchema.js
- /usr/local/lib/node_modules/prisma-aurora/lib/helpers/index.js
- /usr/local/lib/node_modules/prisma-aurora/lib/aurora.js
- /usr/local/lib/node_modules/prisma-aurora/lib/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/prisma-aurora/node_modules/@prisma/sdk/dist/utils/jestContext.js:30:36)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/prisma-aurora/node_modules/@prisma/sdk/dist/utils/jestContext.js',
    '/usr/local/lib/node_modules/prisma-aurora/node_modules/@prisma/sdk/dist/index.js',
    '/usr/local/lib/node_modules/prisma-aurora/lib/helpers/parseSchema.js',
    '/usr/local/lib/node_modules/prisma-aurora/lib/helpers/index.js',
    '/usr/local/lib/node_modules/prisma-aurora/lib/aurora.js',
    '/usr/local/lib/node_modules/prisma-aurora/lib/index.js'
  ]
}
```

Do you hava this error too ?

Thanks,

**Comment by sabinadams** [comment]
Hi @Gouet! I just ran a fresh install and I did not see the same error you ran into.

Have you tried blowing out your node_modules and re-installing?

**Comment by sabinadams** [comment]
Nevermind! This is an issue with Prisma's internals itself in the new `v3.8.0`, as referenced [here](https://github.com/prisma/prisma/issues/11126)

It looks like Prisma `v3.9.0` should fix it. In the meantime, bumping back to `v3.7.0`.
