### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by ddhorstman** [sabinadams/aurora#57]
**Describe the bug**
Aurora will combine the example schemas, but it refuses to combine mine. It throws an uncaught `TypeError` from the source code itself (see screenshot below).

**To Reproduce**
1. Run `npm i -D prisma-aurora`
2. Use this `aurora.config.json`:
```
{
  "files": [
    "./user-model.prisma",
    "./worker-model.prisma"
  ],
  "output": "./schema-new.prisma"
}
```
3. Create these two files:
### `user-model.prisma`:
```
datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_URI")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["filterJson", "interactiveTransactions"]
}

model User {
  id        Int     @id @default(autoincrement())
  firstName String  @map("first_name")
  lastName  String  @map("last_name")
  // fullName is a computed property in Postgres
  // I've made it optional since it should never be set
  // However, it will always have a value.
  // If you try to set it, your request will fail with an error
  fullName  String? @map("full_name")

  // Users must have an email address or phone number
  // They needn't specify both
  email String? @unique
  phone String? @unique


  // Used to pay out referral bonuses
  referralCode String? @map("referral_code")

  // Auditing fields
  deleted   Boolean  @default(false)
  createdAt DateTime @default(now()) @map("created_at")
  updatedAt DateTime @updatedAt @map("updated_at")

  // A user can send multiple referrals, but can only consume one
  referralsSent    Referral[] @relation("referrals_sent")
  referralConsumed Referral?  @relation("referral_consumed")
  @@map("users")
}

//---------------------------------- Referrals -------------------------------------------//
model Referral {
  id Int @id

  sentBy       User @relation("referrals_sent", fields: [senderUserId], references: [id])
  senderUserId Int  @map("sender_user_id")

  consumedBy     User @relation("referral_consumed", fields: [consumerUserId], references: [id])
  consumerUserId Int  @unique @map("consumer_user_id")

  status ReferralStatus

  senderBonusAmount   Decimal @default(50) @map("sender_bonus_amount") @db.Decimal(10, 2)
  consumerBonusAmount Decimal @default(50) @map("consumer_bonus_amount") @db.Decimal(10, 2)

  @@map("referrals")
}

enum ReferralStatus {
  CREATED
  SHIFT_WORKED
  PAID

  @@map("referral_status")
}
```
### `worker-model.prisma`:
```
datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_URI")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["filterJson", "interactiveTransactions"]
}

//--------------------------------------------------------------------------------------------------//
//-------------------------------------- Full Models ----------------------------------------------//
//------------------------------------------------------------------------------------------------//
enum WorkerStatus {
  ACTIVE
  PROBATION
  SUSPENDED
  PAUSED
  DISABLED
  ONBOARDING
  ENROLLED

  @@map("worker_status")
}

model Worker {
  // We're using the same primary id as 'users' for simplicity
  userId Int  @id @map("user_id")
  user   User @relation(fields: [userId], references: [id])

  // Auditing fields
  deleted   Boolean  @default(false)
  createdAt DateTime @default(now()) @map("created_at")
  updatedAt DateTime @default(now()) @updatedAt @map("updated_at")

  status WorkerStatus @default(ACTIVE)

  maximumShiftDistanceMiles Int @default(150) @map("maximum_shift_distance_miles")
  unexcusedNoCallNoShows    Int @default(0) @map("unexcused_no_call_no_shows")

  @@map("workers")
}

//--------------------------------------------------------------------------------------------------//
//----------------------------- Partial Models for Relations --------------------------------------//
//------------------------------------------------------------------------------------------------//
model User {
  id     Int     @id
  worker Worker?
}

```
4. Run `aurora`

**Expected behavior**
The two schemas are combined into a single `new-schema.prisma`

**Actual Behavior**
The following error is printed:
```     _                                          
    / \     _   _   _ __    ___    _ __    __ _ 
   / _ \   | | | | | '__|  / _ \  | '__|  / _` |
  / ___ \  | |_| | | |    | (_) | | |    | (_| |
 /_/   \_\  \__,_| |_|     \___/  |_|     \__,_|
                                                
TypeError: Cannot read properties of undefined (reading 'filter')
    at /home/davidhorstman/GitHub/clipboard-staffing-api/node_modules/prisma-aurora/lib/helpers/parseSchema.js:103:84
    at Array.map (<anonymous>)
    at /home/davidhorstman/GitHub/clipboard-staffing-api/node_modules/prisma-aurora/lib/helpers/parseSchema.js:102:59
    at step (/home/davidhorstman/GitHub/clipboard-staffing-api/node_modules/prisma-aurora/lib/helpers/parseSchema.js:44:23)
    at Object.next (/home/davidhorstman/GitHub/clipboard-staffing-api/node_modules/prisma-aurora/lib/helpers/parseSchema.js:25:53)
    at fulfilled (/home/davidhorstman/GitHub/clipboard-staffing-api/node_modules/prisma-aurora/lib/helpers/parseSchema.js:16:58) Aurora could not parse the schema at ./src/modules/workers/worker-model.prisma. Please ensure it is of a proper format.
/home/davidhorstman/GitHub/clipboard-staffing-api/node_modules/prisma-aurora/lib/helpers/parseSchema.js:103
                                model.extendedFields = attributeData_1[model.name].filter(function (attribute) { return attribute.isFieldAttribute; });
                                                                                   ^

TypeError: Cannot read properties of undefined (reading 'filter')
    at /home/davidhorstman/GitHub/clipboard-staffing-api/node_modules/prisma-aurora/lib/helpers/parseSchema.js:103:84
    at Array.map (<anonymous>)
    at /home/davidhorstman/GitHub/clipboard-staffing-api/node_modules/prisma-aurora/lib/helpers/parseSchema.js:102:59
    at step (/home/davidhorstman/GitHub/clipboard-staffing-api/node_modules/prisma-aurora/lib/helpers/parseSchema.js:44:23)
    at Object.next (/home/davidhorstman/GitHub/clipboard-staffing-api/node_modules/prisma-aurora/lib/helpers/parseSchema.js:25:53)
    at fulfilled (/home/davidhorstman/GitHub/clipboard-staffing-api/node_modules/prisma-aurora/lib/helpers/parseSchema.js:16:58)
```

**Desktop (please complete the following information):**
 - OS: Windows 10, WSL2 (Ubuntu 20.04)

**Screenshots**
![image](https://user-images.githubusercontent.com/7649736/154740810-8eea193d-775f-42e4-bb63-c6ed954fd82a.png)

**Additional context**
Both schemas were lifted from an original single schema with the only change being moving the relation from the full `User` schema to the partial schema next to `Worker`. I am able to recombine them using `prismix`.

**Comment by sabinadams** [comment]
I can't seem to recreate this issue. Can you paste in the schema you are using?

**Comment by cmd-johnson** [comment]
I'm encountering that same issue. It occurs every time I'm using comments before defining a model:

- Works:
    ```prisma
    model ModelA {
      // Comment
      id Int @id
    }
    ```

- Fails:
    ```prisma
    // Comment
    model ModelA {
      id Int @id
    }
    ```

Both using Aurora 1.3.3 running with node v16.13.0 on linux, with the following config:
```json
{
  "files": [
    "./modelA.prisma"
  ],
  "output": "./schema.prisma"
}
```

<details>
<summary>Error Output</summary>

```
TypeError: Cannot read properties of undefined (reading 'filter')
    at /tmp/xfs-9f75d524/dlx-74100/node_modules/prisma-aurora/lib/helpers/parseSchema.js:103:84
    at Array.map (<anonymous>)
    at /tmp/xfs-9f75d524/dlx-74100/node_modules/prisma-aurora/lib/helpers/parseSchema.js:102:59
    at step (/tmp/xfs-9f75d524/dlx-74100/node_modules/prisma-aurora/lib/helpers/parseSchema.js:44:23)
    at Object.next (/tmp/xfs-9f75d524/dlx-74100/node_modules/prisma-aurora/lib/helpers/parseSchema.js:25:53)
    at fulfilled (/tmp/xfs-9f75d524/dlx-74100/node_modules/prisma-aurora/lib/helpers/parseSchema.js:16:58) Aurora could not parse the schema at ./modelA.prisma. Please ensure it is of a proper format.
/tmp/xfs-9f75d524/dlx-74100/node_modules/prisma-aurora/lib/helpers/parseSchema.js:103
                                model.extendedFields = attributeData_1[model.name].filter(function (attribute) { return attribute.isFieldAttribute; });
                                                                                   ^

TypeError: Cannot read properties of undefined (reading 'filter')
    at /tmp/xfs-9f75d524/dlx-74100/node_modules/prisma-aurora/lib/helpers/parseSchema.js:103:84
    at Array.map (<anonymous>)
    at /tmp/xfs-9f75d524/dlx-74100/node_modules/prisma-aurora/lib/helpers/parseSchema.js:102:59
    at step (/tmp/xfs-9f75d524/dlx-74100/node_modules/prisma-aurora/lib/helpers/parseSchema.js:44:23)
    at Object.next (/tmp/xfs-9f75d524/dlx-74100/node_modules/prisma-aurora/lib/helpers/parseSchema.js:25:53)
    at fulfilled (/tmp/xfs-9f75d524/dlx-74100/node_modules/prisma-aurora/lib/helpers/parseSchema.js:16:58)
```
</details>

Comments before `datasource`, `generator` and `enum` definitions work fine:
```prisma
// Comment
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// Comment
generator client {
  provider = "prisma-client-js"
}

// Comment
enum TestEnum {
  TEST
}
```
